github: draldric
custom: ["https://www.paypal.com/donate/?business=X9N7J39L36S9U&no_recurring=0&item_name=Your+contribution%2C+no+matter+how+big+or+small%2C+helps+me+cover+the+costs+of+maintaining+this+website.&currency_code=CAD"."donate@daniel-aldrich.ca"]
